### ISSUE TITLE
Any demos/examples in use?

### ISSUE THREAD

**Issue by callumlocke** [nikhilnxvverma1/number-line#2]
This library looks really useful, thanks for writing it!

The readme says

> There are several tutorials on how to draw a simple number line

Can you point me to any tutorials or demos, ideally using this specific library, so I can get a better idea how to use it?

**Comment by nikhilnxvverma1** [comment]
Hello, currently I am a bit busy atm but I ensured the the library stays as vanilla and thoroughly documented so someone can pick it up. I have conceptualized ideas for making it far more flexible radically extending its versatality to games, graphing calculators, infographics etc. Thanks for reaching out. 

While I can't contribute in the immediate window, can you describe me your requirements? maybe I can give you some pointers.

**Comment by nikhilverma-xorsafe-0** [comment]
Hello sorry for the delay. But v2 is out now. It's far simpler than before. I also updated the documentation with example for how to use. Hope this helps

**Comment by callumlocke** [comment]
Only just saw this v2 update, awesome, thanks! I'm looking into it now, looks great at first glance
